services:
  nginx:
    image: nginx:latest
    container_name: aigateway_nginx

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

    networks:
      - shared_net

networks:
  shared_net:
    external: true
